"""Từ khóa và mẫu regex cho các danh mục Cán bộ giảng viên, NCKH, Tin tức sự kiện."""
from __future__ import annotations

ORG_PATTERNS: dict[str, list[str]] = {
    "CAN_BO_GIANG_VIEN": [
        r'\bcan[-_ ]?bo\b',
        r'\bgiang[-_ ]?vien\b',
        r'\bnhan[-_ ]?su\b',
        r'\bbo[-_ ]?mon\b',
        r'\bban[-_ ]?chu[-_ ]?nhiem\b',
        r'\bban[-_ ]?lanh[-_ ]?dao\b',
        r'\bly[-_ ]?lich[-_ ]?khoa[-_ ]?hoc\b',
        r'\bly[-_ ]?lich\b',
        r'\bcurriculum[-_ ]?vitae\b',
        r'\bfaculty\b',
        r'\bstaff\b',
        r'\blecturer\b',
        r'\bprofessor\b',
        r'\bgiao[-_ ]?su\b',
        r'\bpho[-_ ]?giao[-_ ]?su\b',
        r'\bchuyen[-_ ]?gia\b',
        r'\bdanh[-_ ]?sach[-_ ]?can[-_ ]?bo\b',
        r'\bdoi[-_ ]?ngu\b',
        r'\bphong[-_ ]?thi[-_ ]?nghiem\b',
    ],
    "NGHIEN_CUU_HOP_TAC": [
        r'\bnghien[-_ ]?cuu\b',
        r'\bnckh\b',
        r'\bsvnckh\b',
        r'\bkhoa[-_ ]?hoc[-_ ]?cong[-_ ]?nghe\b',
        r'\bkhcn\b',
        r'\bhoi[-_ ]?thao\b',
        r'\bhoi[-_ ]?nghi\b',
        r'\bconference\b',
        r'\bworkshop\b',
        r'\bseminar\b',
        r'\bsymposium\b',
        r'\bde[-_ ]?tai\b',
        r'\bdu[-_ ]?an\b',
        r'\bproject\b',
        r'\bcong[-_ ]?bo\b',
        r'\bbai[-_ ]?bao\b',
        r'\btap[-_ ]?chi\b',
        r'\bpublication\b',
        r'\bpatent\b',
        r'\bsang[-_ ]?che\b',
        r'\bhop[-_ ]?tac\b',
        r'\bdoi[-_ ]?ngoai\b',
        r'\binternational\b',
        r'\bquoc[-_ ]?te\b',
        r'\bhoc[-_ ]?bong\b',
        r'\bscholarship\b',
        r'\btrao[-_ ]?doi\b',
        r'\bexchange\b',
        r'\bdoanh[-_ ]?nghiep\b',
        r'\btai[-_ ]?tro\b',
        r'\bmou\b',
        r'\blab\b',
        r'\bpartner\b',
    ],
    "TIN_TUC_SU_KIEN": [
        r'\btin[-_ ]?tuc\b',
        r'\bnews\b',
        r'\bsu[-_ ]?kien\b',
        r'\bevent\b',
        r'\bevents\b',
        r'\bthong[-_ ]?bao\b',
        r'\bannouncement\b',
        r'\bnotice\b',
        r'\bhoat[-_ ]?dong\b',
        r'\bphong[-_ ]?trao\b',
        r'\bdoan[-_ ]?thanh[-_ ]?nien\b',
        r'\bhoi[-_ ]?sinh[-_ ]?vien\b',
        r'\bcuu[-_ ]?sinh[-_ ]?vien\b',
        r'\balumni\b',
        r'\bkhai[-_ ]?giang\b',
        r'\bbe[-_ ]?giang\b',
        r'\ble[-_ ]?tot[-_ ]?nghiep\b',
        r'\btrao[-_ ]?bang\b',
        r'\bgiai[-_ ]?thuong\b',
        r'\bvinh[-_ ]?danh\b',
        r'\btuyen[-_ ]?duong\b',
        r'\bcuoc[-_ ]?thi\b',
        r'\bhackathon\b',
        r'\bgiao[-_ ]?luu\b',
        r'\bgap[-_ ]?mat\b',
        r'\btoa[-_ ]?dam\b',
        r'\btuyen[-_ ]?dung\b',
        r'\bviec[-_ ]?lam\b',
    ],
}
