"""Từ khóa và mẫu regex cho các danh mục Đào tạo, Tuyển sinh, Quy chế."""
from __future__ import annotations

EDU_PATTERNS: dict[str, list[str]] = {
    "TUYEN_SINH": [
        r'\btuyen[-_ ]?sinh\b',
        r'\bxet[-_ ]?tuyen\b',
        r'\bthi[-_ ]?tuyen\b',
        r'\bnhap[-_ ]?hoc\b',
        r'\bdiem[-_ ]?chuan\b',
        r'\bchi[-_ ]?tieu\b',
        r'\bde[-_ ]?an[-_ ]?tuyen[-_ ]?sinh\b',
        r'\badmission\b',
        r'\badmissions\b',
        r'\benrollment\b',
        r'\btan[-_ ]?sinh[-_ ]?vien\b',
        r'\btuyen[-_ ]?thanh\b',
    ],
    "QUY_CHE_BIEU_MAU": [
        r'\bquy[-_ ]?che\b',
        r'\bquy[-_ ]?dinh\b',
        r'\bbieu[-_ ]?mau\b',
        r'\bmau[-_ ]?don\b',
        r'\bdon[-_ ]?tu\b',
        r'\bhoc[-_ ]?phi\b',
        r'\bthu[-_ ]?tuc\b',
        r'\bquy[-_ ]?trinh\b',
        r'\bso[-_ ]?tay[-_ ]?sinh[-_ ]?vien\b',
        r'\bnoi[-_ ]?quy\b',
        r'\bdieu[-_ ]?le\b',
        r'\bchuan[-_ ]?dau[-_ ]?ra[-_ ]?ngoai[-_ ]?ngu\b',
        r'\bchuan[-_ ]?tieng[-_ ]?anh\b',
        r'\bvstep\b',
        r'\btoeic\b',
        r'\bielts\b',
        r'\bvan[-_ ]?ban[-_ ]?quy[-_ ]?pham\b',
        r'\bhoc[-_ ]?bong[-_ ]?khuyen[-_ ]?khich\b',
        r'\bche[-_ ]?do[-_ ]?chinh[-_ ]?sach\b',
    ],
    "DAO_TAO": [
        r'\bdao[-_ ]?tao\b',
        r'\bchuong[-_ ]?trinh[-_ ]?dao[-_ ]?tao\b',
        r'\bctdt\b',
        r'\bkhung[-_ ]?chuong[-_ ]?trinh\b',
        r'\bmon[-_ ]?hoc\b',
        r'\bhoc[-_ ]?phan\b',
        r'\btin[-_ ]?chi\b',
        r'\bthoi[-_ ]?khoa[-_ ]?bieu\b',
        r'\btkb\b',
        r'\blich[-_ ]?thi\b',
        r'\blich[-_ ]?hoc\b',
        r'\bchuan[-_ ]?dau[-_ ]?ra\b',
        r'\bdai[-_ ]?hoc\b',
        r'\bsau[-_ ]?dai[-_ ]?hoc\b',
        r'\bthac[-_ ]?si\b',
        r'\btien[-_ ]?si\b',
        r'\bcao[-_ ]?hoc\b',
        r'\bcu[-_ ]?nhan\b',
        r'\bky[-_ ]?su\b',
        r'\bkhoa[-_ ]?luan\b',
        r'\bkltn\b',
        r'\bdo[-_ ]?an\b',
        r'\bdatn\b',
        r'\btot[-_ ]?nghiep\b',
        r'\bhoc[-_ ]?vu\b',
        r'\bgiao[-_ ]?trinh\b',
        r'\bde[-_ ]?cuong\b',
        r'\bsyllabus\b',
        r'\bchuyen[-_ ]?nganh\b',
        r'\bnganh[-_ ]?hoc\b',
        r'\blop[-_ ]?hoc[-_ ]?phan\b',
        r'\bket[-_ ]?qua[-_ ]?hoc[-_ ]?tap\b',
    ],
}
